<?php

namespace AppBundle\Repository;


/**
 * VelibRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VelibRepository extends \Doctrine\ORM\EntityRepository
{
}
