app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

velibs:
    type:     rest
    resource: AppBundle\Controller\ApiController